import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Image from "next/image";
import { Footer } from "~/components/ui/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} dark`}>
        <div className="flex flex-col h-screen w-screen items-center justify-center bg-gradient-to-b from-slate-300 to-slate-700">
          <div className="flex flex-col w-9/12 h-3/4 justify-between bg-slate-200 rounded p-4">
            <div className="w-auto h-28 relative rounded">
              <Image src={"/logo.png"} alt="icon" fill></Image>
            </div>
            <div>
              {children}
            </div>
            <Footer></Footer>
          </div>
        </div>
      </body>
    </html >
  );
}
